name: Rust

on:
  push:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '.github/workflows/rust.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '.github/workflows/rust.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust Toolchain
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly build --all-features --verbose
    - name: Run tests
      run: cargo +nightly test --all-features --verbose
